/*    ==Scripting Parameters==

    Source Server Version : SQL Server 2016 (13.0.4001)
    Source Database Engine Edition : Microsoft SQL Server Express Edition
    Source Database Engine Type : Standalone SQL Server

    Target Server Version : SQL Server 2016
    Target Database Engine Edition : Microsoft SQL Server Express Edition
    Target Database Engine Type : Standalone SQL Server
*/

USE [master]
GO

/****** Object:  Database [training_log]    Script Date: 11/23/2019 4:44:28 PM ******/
CREATE DATABASE [training_log]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'training_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\training_log.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'training_log_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\training_log_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [training_log] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [training_log].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [training_log] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [training_log] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [training_log] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [training_log] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [training_log] SET ARITHABORT OFF 
GO

ALTER DATABASE [training_log] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [training_log] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [training_log] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [training_log] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [training_log] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [training_log] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [training_log] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [training_log] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [training_log] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [training_log] SET  DISABLE_BROKER 
GO

ALTER DATABASE [training_log] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [training_log] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [training_log] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [training_log] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [training_log] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [training_log] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [training_log] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [training_log] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [training_log] SET  MULTI_USER 
GO

ALTER DATABASE [training_log] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [training_log] SET DB_CHAINING OFF 
GO

ALTER DATABASE [training_log] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [training_log] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [training_log] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [training_log] SET QUERY_STORE = OFF
GO

USE [training_log]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [training_log] SET  READ_WRITE 
GO

